[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install --production",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "node app.js"
